In [3]:
import pandas as pd
import numpy as np


In [4]:
pd.__version__

'2.2.2'

In [14]:
## Download the data using wget

url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"

laptop_df = pd.read_csv(url)
laptop_df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

What is the number of records? len(df)

What is the number of unique brand?

In [16]:
laptop_df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

What are the NA?

In [18]:
laptop_df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

What's the maximum final price of Dell notebooks in the dataset?


In [25]:
laptop_df.groupby('Brand')['Final Price'].max()

Brand
Acer                3691.00
Alurin               869.00
Apple               3849.00
Asus                5758.14
Deep Gaming         1639.01
Dell                3936.00
Denver               329.95
Dynabook Toshiba    1805.01
Gigabyte            3799.00
HP                  5368.77
Innjoo               431.38
Jetwing              469.27
LG                  2399.00
Lenovo              5018.14
MSI                 7150.47
Medion              3799.00
Microsoft           3747.91
Millenium           2312.71
PcCom               1949.90
Primux               599.41
Prixton              329.95
Razer               4999.01
Realme               999.00
Samsung             3699.01
Thomson              436.56
Toshiba              799.00
Vant                1217.01
Name: Final Price, dtype: float64

Find the median value of Screen column in the dataset.
Next, calculate the most frequent value of the same Screen column.
Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
Now, calculate the median value of Screen once again.
Has it changed?

Hint: refer to existing mode and median functions to complete the task.

In [26]:
laptop_df['Screen'].median()

15.6

In [28]:
mode = laptop_df['Screen'].mode()
mode

0    15.6
Name: Screen, dtype: float64

In [29]:
laptop_df['Screen'] = laptop_df['Screen'].fillna(mode)

In [30]:
laptop_df['Screen'].median()

15.6

- Select all the "Innjoo" laptops from the dataset.
- 
Select only columns RAM, Storage, Screen.- 
Get the underlying NumPy array. Let's call it X- .
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XT- X.
Compute the inverse of X- TX.
Create an array y with values [1100, 1300, 800, 900, 1000, 11- 00].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the resu- lt w.
What's the sum of all the elements of the r lesson.

In [42]:
Innjoo_laptop = laptop_df[laptop_df['Brand'] == "Innjoo"]
sub_df = Innjoo_laptop[['RAM', 'Storage', 'Screen']]
sub_df

RAM  Storage  Screen
0       8      512    15.6
1       8      256    15.6
2       8      256    15.6
3      16     1000    15.6
4      16      512    15.6
...   ...      ...     ...
2155   16     1000    17.3
2156   16     1000    17.3
2157   32     1000    17.3
2158   16     1000    13.4
2159   16      256    13.4

[2160 rows x 3 columns]

In [55]:
# Convert dataframe to numpy array
X = sub_df.to_numpy()
X

array([[   8. ,  512. ,   15.6],
       [   8. ,  256. ,   15.6],
       [   8. ,  256. ,   15.6],
       ...,
       [  32. , 1000. ,   17.3],
       [  16. , 1000. ,   13.4],
       [  16. ,  256. ,   13.4]])

In [90]:
# The transpose of X
XT = X.T

XT

array([[   8. ,    8. ,    8. , ...,   32. ,   16. ,   16. ],
       [ 512. ,  256. ,  256. , ..., 1000. , 1000. ,  256. ],
       [  15.6,   15.6,   15.6, ...,   17.3,   13.4,   13.4]])

In [91]:
# Matrix_matrix multiplication between X and XT
XTX = X.dot(XT)


XTX

array([[ 262451.36,  131379.36,  131379.36, ...,  512525.88,  512337.04,
         131409.04],
       [ 131379.36,   65843.36,   65843.36, ...,  256525.88,  256337.04,
          65873.04],
       [ 131379.36,   65843.36,   65843.36, ...,  256525.88,  256337.04,
          65873.04],
       ...,
       [ 512525.88,  256525.88,  256525.88, ..., 1001323.29, 1000743.82,
         256743.82],
       [ 512337.04,  256337.04,  256337.04, ..., 1000743.82, 1000435.56,
         256435.56],
       [ 131409.04,   65873.04,   65873.04, ...,  256743.82,  256435.56,
          65971.56]])

In [92]:
# Inverse of the result
import numpy as np
XTX_inv = np.linalg.inv(XTX)

XTX_inv

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [93]:
# Create array y
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [94]:
w = (XT * XTX_inv) * y

ValueError: operands could not be broadcast together with shapes (3,2160) (2160,2160) 